version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rust
    versions:
    - 1.49.0.pre.slim.pre.buster
    - 1.50.0.pre.slim.pre.buster
